//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepreciationCalculator.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageEn() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DepreciationCalculator.Languages.LanguageEn", typeof(LanguageEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CALCULATE.
        /// </summary>
        internal static string btnCalcular {
            get {
                return ResourceManager.GetString("btnCalcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SPANISH.
        /// </summary>
        internal static string btnEspanol {
            get {
                return ResourceManager.GetString("btnEspanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENGLISH.
        /// </summary>
        internal static string btnIngles {
            get {
                return ResourceManager.GetString("btnIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LIGHT.
        /// </summary>
        internal static string btnModoDeColor1 {
            get {
                return ResourceManager.GetString("btnModoDeColor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DARK.
        /// </summary>
        internal static string btnModoDeColor2 {
            get {
                return ResourceManager.GetString("btnModoDeColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PORTUGUESE.
        /// </summary>
        internal static string btnPortuges {
            get {
                return ResourceManager.GetString("btnPortuges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string daBtnNo {
            get {
                return ResourceManager.GetString("daBtnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string daBtnYes {
            get {
                return ResourceManager.GetString("daBtnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To set the chosen language, run the application again..
        /// </summary>
        internal static string daMessage {
            get {
                return ResourceManager.GetString("daMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLOSE APPLICATION.
        /// </summary>
        internal static string daTittle {
            get {
                return ResourceManager.GetString("daTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the asset&apos;s initial value.
        /// </summary>
        internal static string inputValorInicial {
            get {
                return ResourceManager.GetString("inputValorInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the asset&apos;s useful life in years.
        /// </summary>
        internal static string inputVidaUtil {
            get {
                return ResourceManager.GetString("inputVidaUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CALCULATE DEPRECIATION OF YOUR FIXED ASSETS.
        /// </summary>
        internal static string lb1page1 {
            get {
                return ResourceManager.GetString("lb1page1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your language.
        /// </summary>
        internal static string lb1page2 {
            get {
                return ResourceManager.GetString("lb1page2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LINEAR DEPRECIATION.
        /// </summary>
        internal static string lb2page1 {
            get {
                return ResourceManager.GetString("lb2page1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change color mode.
        /// </summary>
        internal static string lb2page2 {
            get {
                return ResourceManager.GetString("lb2page2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ....
        /// </summary>
        internal static string lbDepreciacion {
            get {
                return ResourceManager.GetString("lbDepreciacion", resourceCulture);
            }
        }
    }
}
